/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as BuyerImport } from './routes/_buyer'
import { Route as IndexImport } from './routes/index'
import { Route as BuyerLikedIndexImport } from './routes/_buyer.liked.index'
import { Route as BuyerDiscoverIndexImport } from './routes/_buyer.discover.index'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const BuyerRoute = BuyerImport.update({
  id: '/_buyer',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BuyerLikedIndexRoute = BuyerLikedIndexImport.update({
  id: '/liked/',
  path: '/liked/',
  getParentRoute: () => BuyerRoute,
} as any)

const BuyerDiscoverIndexRoute = BuyerDiscoverIndexImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => BuyerRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_buyer': {
      id: '/_buyer'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BuyerImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_buyer/discover/': {
      id: '/_buyer/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof BuyerDiscoverIndexImport
      parentRoute: typeof BuyerImport
    }
    '/_buyer/liked/': {
      id: '/_buyer/liked/'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof BuyerLikedIndexImport
      parentRoute: typeof BuyerImport
    }
  }
}

// Create and export the route tree

interface BuyerRouteChildren {
  BuyerDiscoverIndexRoute: typeof BuyerDiscoverIndexRoute
  BuyerLikedIndexRoute: typeof BuyerLikedIndexRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerDiscoverIndexRoute: BuyerDiscoverIndexRoute,
  BuyerLikedIndexRoute: BuyerLikedIndexRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof BuyerRouteWithChildren
  '/signup': typeof SignupRoute
  '/discover': typeof BuyerDiscoverIndexRoute
  '/liked': typeof BuyerLikedIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof BuyerRouteWithChildren
  '/signup': typeof SignupRoute
  '/discover': typeof BuyerDiscoverIndexRoute
  '/liked': typeof BuyerLikedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_buyer': typeof BuyerRouteWithChildren
  '/signup': typeof SignupRoute
  '/_buyer/discover/': typeof BuyerDiscoverIndexRoute
  '/_buyer/liked/': typeof BuyerLikedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/signup' | '/discover' | '/liked'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/signup' | '/discover' | '/liked'
  id:
    | '__root__'
    | '/'
    | '/_buyer'
    | '/signup'
    | '/_buyer/discover/'
    | '/_buyer/liked/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerRoute: BuyerRouteWithChildren,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_buyer",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_buyer": {
      "filePath": "_buyer.tsx",
      "children": [
        "/_buyer/discover/",
        "/_buyer/liked/"
      ]
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_buyer/discover/": {
      "filePath": "_buyer.discover.index.tsx",
      "parent": "/_buyer"
    },
    "/_buyer/liked/": {
      "filePath": "_buyer.liked.index.tsx",
      "parent": "/_buyer"
    }
  }
}
ROUTE_MANIFEST_END */
